import {
    Button,
    VerticalBox,
    ComboBox,
    StandardButton,
    TabWidget,
    HorizontalBox,
    GroupBox,
} from "std-widgets.slint";

import "../../assets/fonts/Lilex/Lilex-Regular.ttf";

component CustomDropdown inherits Rectangle {
    in property <[string]> values: ["Option 1", "Option 2", "Option 3"];
    in-out property <int> current-index: 0;
    border-width: 1px;
    border-color: #16161621;
    Text {
        text: "EzYDark";
        color: #fff;
        font-size: 14px;
        vertical-alignment: center;
        x: 8px;
        height: parent.height;
        width: parent.width;
    }

    TouchArea {
        width: parent.width;
        height: parent.height;
        mouse-cursor: pointer;
        clicked => {
            menu.show();
        }
    }

    menu := PopupWindow {
        x: 0px;
        y: root.height;
        width: root.width;
        Rectangle {
            background: #252525;
            border-width: 1px;
            border-color: #16161621;
            VerticalLayout {
                padding: 4px;
                spacing: 2px;
                for value[index] in root.values: Rectangle {
                    height: 32px;
                    background: area.has-hover ? #3c3c3c : transparent;
                    border-radius: 2px;
                    Text {
                        text: value;
                        color: white;
                        font-size: 14px;
                        vertical-alignment: center;
                        x: 8px;
                    }

                    area := TouchArea {
                        mouse-cursor: pointer;
                        clicked => {
                            root.current-index = index;
                            menu.close();
                        }
                    }
                }
            }
        }
    }
}

export component AppWindow inherits Window {
    preferred-width: 800px;
    preferred-height: 600px;
    min-width: 1px;
    min-height: 1px;
    max-width: 99999px;
    max-height: 99999px;
    default-font-family: "Lilex";
    Rectangle {
        background: #161616;
        HorizontalLayout {
            // Left Sidebar
            Rectangle {
                width: 74px;
                background: #45284f;
            }

            // Secondary Sidebar
            Rectangle {
                width: 250px;
                background: #284f3f;
                VerticalLayout {
                    CustomDropdown {
                        height: 40px;
                        values: ["Dashboard", "Settings", "Profile", "Logout"];
                        background: #1c1c1c9b;
                    }
                }
            }

            // Main Content Bar
            Rectangle {
                background: #181741;
            }

            // Right Sidebar
            Rectangle {
                width: 250px;
                background: #404117;
            }
        }
    }
}
