export component CustomButton inherits Rectangle {
    in property <string> text: "Button";
    callback clicked;
    border-width: 1px;
    border-color: #3c3c3c;
    background: touch-area.pressed ? #2e2e2e : #1f1f1f;
    touch-area := TouchArea {
        width: parent.width;
        height: parent.height;
        mouse-cursor: pointer;
        clicked => root.clicked();
    }

    Text {
        text: root.text;
        color: #f5f5f5;
        font-size: 15px;
        horizontal-alignment: center;
        vertical-alignment: center;
    }
}
