import "../../assets/fonts/Lilex/Lilex-Regular.ttf";
import "../../assets/fonts/Lilex/Lilex-Bold.ttf";
import "../../assets/fonts/Lilex/Lilex-Italic.ttf";
import { Dropdown, DropdownItem } from "dropdown.slint";
import { HorizontalBox } from "std-widgets.slint";
import { Palette } from "palette.slint";
import { LeftSidebar } from "left-sidebar.slint";
import { ChannelsList } from "channels-list.slint";

export component AppWindow inherits Window {
    preferred-width: 800px;
    preferred-height: 600px;
    min-width: 1px;
    min-height: 1px;
    max-width: 99999px;
    max-height: 99999px;
    default-font-family: "Lilex";
    Rectangle {
        background: Palette.background;
        HorizontalLayout {
            // Left Sidebar
            Rectangle {
                width: 74px;
                border-width: 0.5px;
                border-color: Palette.border;
                background: Palette.background-dark;
                LeftSidebar { }
            }

            // Secondary Sidebar
            Rectangle {
                border-width: 0.5px;
                border-color: Palette.border;
                width: 250px;
                background: Palette.background-dark;
                VerticalLayout {
                    // Server options
                    dp := Dropdown {
                        text: "EzYDark";
                        height: 46px;
                        DropdownItem {
                            height: 36px;
                            text: "Invite People";
                            clicked => {
                                debug("Selected Invite People");
                                dp.close();
                            }
                        }

                        DropdownItem {
                            height: 36px;
                            text: "Server Settings";
                            clicked => {
                                debug("Selected Server Settings");
                                dp.close();
                            }
                        }

                        DropdownItem {
                            height: 36px;
                            text: "Leave Server";
                            clicked => {
                                debug("Selected Leave Server");
                                dp.close();
                            }
                        }
                    }

                    VerticalLayout {
                        // Channels lists
                        ChannelsList { }

                        Rectangle {
                            height: 64px;
                            border-width: 0.5px;
                            border-color: Palette.border;
                        }
                    }
                }
            }

            // Main Content Bar
            Rectangle {
                background: Palette.background;
                border-width: 0.5px;
                border-color: Palette.border;
            }

            // Right Sidebar
            Rectangle {
                width: 250px;
                background: Palette.background-dark;
                border-width: 0.5px;
                border-color: Palette.border;
            }
        }
    }
}
