import { Palette } from "palette.slint";

export component DropdownItem {
    in property <string> text: "ItemText";
    in property <brush> background: transparent;
    in property <brush> hover-color: Palette.selection;
    callback clicked;
    Rectangle {
        height: root.height;
        width: root.width;
        background: item-touch.has-hover ? root.hover-color : root.background;
        animate background { duration: 50ms; }
        Text {
            width: root.width;
            font-size: 13px;
            text: root.text;
            x: 10px;
        }

        item-touch := TouchArea {
            mouse-cursor: pointer;
            clicked => {
                root.clicked();
            }
        }
    }
}

export component Dropdown {
    in property <string> text: "ButtonText";
    in property <brush> background: Palette.background-dark;
    in property <brush> hover-color: Palette.selection;
    in property <brush> border-color: Palette.border;
    in property <brush> menu-background: Palette.background-darker;

    // Dropdown button
    Rectangle {
        border-width: 0.5px;
        border-color: root.border-color;
        background: button-touch.has-hover ? root.hover-color : root.background;
        animate background { duration: 150ms; }
        height: root.height;
        width: root.width;
        VerticalLayout {
            alignment: center;
            HorizontalLayout {
                padding: 10px;
                Text {
                    font-size: 15px;
                    font-weight: 700;
                    text: text;
                }

                Image {
                    source: @image-url("../assets/icons/chevron-down.svg");
                    height: 16px;
                    width: 16px;
                    colorize: white;
                }
            }
        }

        button-touch := TouchArea {
            mouse-cursor: pointer;
            clicked => {
                menu.show();
            }
        }
    }

    public function close() {
        menu.close();
    }

    //Dropdown menu
    menu := PopupWindow {
        close-policy: close-on-click-outside;
        y: root.height;
        width: root.width;
        Rectangle {
            background: root.menu-background;
            border-width: 0.5px;
            border-color: root.border-color;
            VerticalLayout {
                @children
            }
        }
    }
}
