import "../assets/fonts/Lilex/Lilex-Regular.ttf";
import "../assets/fonts/Lilex/Lilex-Bold.ttf";
import "../assets/fonts/Lilex/Lilex-Italic.ttf";
import { Palette } from "palette.slint";
import { Button } from "std-widgets.slint";


export component AppWindow inherits Window {
    preferred-width: 1280px;
    preferred-height: 720px;
    min-width: 1px;
    min-height: 1px;
    max-width: 99999px;
    max-height: 99999px;
    default-font-family: "Lilex";
    no-frame: true;
    resize-border-width: 10px;
    callback start-window-drag();
    callback maximize-window();
    Rectangle {
        background: Palette.background;
        VerticalLayout {
            // Top app bar
            Rectangle {
                height: 32px;
                border-width: 0.5px;
                border-color: Palette.border;
                background: Palette.background-darker;
                TouchArea {
                    width: 100%;
                    height: 100%;
                    pointer-event(event) => {
                        if (event.kind == PointerEventKind.down) {
                            root.start-window-drag();
                        }
                    }
                    double-clicked => {
                        root.maximize-window();
                    }
                }

                HorizontalLayout {
                    // Left side of the app bar
                    VerticalLayout {
                        alignment: center;
                        padding-left: 10px;
                        Text {
                            text: "ezChat";
                        }
                    }

                    // Right side of the app bar
                    VerticalLayout {
                        alignment: center;
                        HorizontalLayout {
                            // Minimize button
                            Rectangle {
                                background: Palette.grey;
                                width: 32px;
                                height: 32px;
                            }

                            // Maximize button
                            Rectangle {
                                background: Palette.yellow;
                                width: 32px;
                                height: 32px;
                            }

                            // Close button
                            Rectangle {
                                background: Palette.red;
                                width: 32px;
                                height: 32px;
                            }
                        }
                    }
                }
            }

            // Main app content
            HorizontalLayout {
                Rectangle {
                    width: 74px;
                    border-width: 0.5px;
                    border-color: Palette.border;
                    background: Palette.background-darker;
                }

                Rectangle {
                    width: 250px;
                    border-width: 0.5px;
                    border-color: Palette.border;
                    background: Palette.background-dark;
                }

                Rectangle {
                    border-width: 0.5px;
                    border-color: Palette.border;
                    background: Palette.background;
                    Rectangle { }
                }

                Rectangle {
                    width: 225px;
                    border-width: 0.5px;
                    border-color: Palette.border;
                    background: Palette.background-darker;
                }
            }
        }
    }
}
