export component DropdownItem {
    in property <string> text: "ItemText"; // Height of each item in the dropdown
    callback clicked;
    Rectangle {
        height: root.height;
        width: root.width;
        background: item-touch.has-hover ? #363636 : transparent;
        Text {
            width: root.width;
            font-size: 14px;
            text: root.text;
            x: 10px;
        }

        item-touch := TouchArea {
            mouse-cursor: pointer;
            clicked => {
                root.clicked();
            }
        }
    }
}

export component Dropdown {
    in property <string> text: "ButtonText"; // Dropdown button text
    in property <brush> background: #1c1c1c9b; // Dropdown button background color

    // Dropdown button
    Rectangle {
        height: root.height;
        width: root.width;
        background: button-touch.has-hover ? root.background.brighter(0.4) : root.background;
        Text {
            font-size: 15px;
            font-weight: 700;
            width: root.width;
            text: text;
            x: 10px;
        }

        button-touch := TouchArea {
            mouse-cursor: pointer;
            clicked => {
                menu.show();
            }
        }
    }

    public function close() {
        menu.close();
    }

    //Dropdown menu
    menu := PopupWindow {
        close-policy: close-on-click-outside;
        y: root.height;
        width: root.width;
        Rectangle {
            background: #1c1c1c;
            VerticalLayout {
                spacing: 2px;
                @children
            }
        }
    }
}
