export global Palette {
    // Base Colors
    out property <brush> background: #2D2A2E;
    out property <brush> background-dark: #221F22;
    out property <brush> background-darker: #19181A;
    out property <brush> background-light: #403E41;
    out property <brush> background-lighter: #5B595C;
    out property <brush> foreground: #FCFCFA;
    
    // Accents
    out property <brush> red: #FF6188;
    out property <brush> orange: #FC9867;
    out property <brush> yellow: #FFD866;
    out property <brush> green: #A9DC76;
    out property <brush> blue: #78DCE8;
    out property <brush> purple: #AB9DF2;
    
    // UI Elements
    out property <brush> grey: #727072;
    out property <brush> black: #19181a;
    out property <brush> border: #2D2A2E;
    out property <brush> border-dark: #1A191B;
    out property <brush> border-light: #5B595C;
    out property <brush> selection: #322d32;

    // ----------------------------------------
    // Other elements
    out property <brush> window-border: #252327;
    out property <brush> minimize-btn-pressed: #3e383e;
    out property <brush> maximize-btn-pressed: #caac51;
    out property <brush> close-btn-pressed: #ba4763;
}
